"""empty message

Revision ID: 1664adaa67db
Revises: e32351475625
Create Date: 2025-04-28 16:56:36.930117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1664adaa67db'
down_revision = 'e32351475625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'professor', ['professor_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'curso', type_='foreignkey')
    # ### end Alembic commands ###
