"""empty message

Revision ID: 24279a325aa9
Revises: 1664adaa67db
Create Date: 2025-04-29 16:52:03.353819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24279a325aa9'
down_revision = '1664adaa67db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'professor', ['professor_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'curso', type_='foreignkey')
    # ### end Alembic commands ###
