"""empty message

Revision ID: 4e34554fc710
Revises: dd021920afcb
Create Date: 2025-04-29 19:31:09.925704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e34554fc710'
down_revision = 'dd021920afcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curso', 'formacao_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'professor', ['professor_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'curso', type_='foreignkey')
    op.alter_column('curso', 'formacao_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
