"""empty message

Revision ID: 635164763ea2
Revises: 8bb995f0dbf9
Create Date: 2025-04-22 19:58:35.076236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635164763ea2'
down_revision = '8bb995f0dbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso', type_='foreignkey')
    # ### end Alembic commands ###
