"""empty message

Revision ID: 67310cc8a83f
Revises: 083b3b680a78
Create Date: 2025-04-22 20:00:48.721146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67310cc8a83f'
down_revision = '083b3b680a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso', type_='foreignkey')
    # ### end Alembic commands ###
