"""empty message

Revision ID: 7906218f3831
Revises: 4e34554fc710
Create Date: 2025-04-30 15:25:41.313489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7906218f3831'
down_revision = '4e34554fc710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'professor', ['professor_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'formacao', ['formacao_id'], ['id'])
    op.add_column('usuario', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'is_admin')
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'curso', type_='foreignkey')
    # ### end Alembic commands ###
