"""empty message

Revision ID: a5f2b2580452
Revises: 24279a325aa9
Create Date: 2025-04-29 16:53:58.540040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f2b2580452'
down_revision = '24279a325aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'formacao', ['formacao_id'], ['id'])
    op.create_foreign_key(None, 'professor_formacao', 'professor', ['professor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'professor_formacao', type_='foreignkey')
    op.drop_constraint(None, 'curso', type_='foreignkey')
    op.drop_table('usuario')
    # ### end Alembic commands ###
