"""empty message

Revision ID: f9d96c669242
Revises: 04e153a421ed
Create Date: 2025-04-24 19:07:43.919157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d96c669242'
down_revision = '04e153a421ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso', type_='foreignkey')
    # ### end Alembic commands ###
