DEBUG = True

#USERNAME = 'postgres'
USERNAME = 'bratus'
PASSWORD = '000000'
SERVER = '192.168.0.217:3306'
#SERVER = '192.168.0.155:5432'
DB = 'api_flask'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
#SQLALCHEMY_DATABASE_URI = f'postgresql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'

SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "aplicacao_flask"